# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.javake.cc/bus
title: 公交来了
email: javake@outlook.com
author: javake
description: > # "Write an awesome description for your new site here. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: Github
    url: https://github.com/javake
  - title: Blog
    url: http://www.javake.cc
  - title: Mail
    url: mailto:javake@outlook.com

apkname:buscoming-1.1.apk