# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.javake.cc/bus
title: 公交来了
email: javake@outlook.com
author: javake
description: > # bus coming , a app for you to know how time will waiting for your bus.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #
apkname: buscoming-1.1.apk
abouttitle: {{ site.abouttitle }}
aboutinfo: {{ site.aboutinfo }}

social:
  - title: Blog
    url: http://javake.cc
    icon: fa-list-alt
  - title: E-Mail
    url: mailto:javake@outlook.com
    icon: fa-envelope-o
