# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://javake.github.io/bus
title: 公交来了
email: javake@outlook.com
author: javake
description: > # bus coming , a app for you to know how time will waiting for your bus.

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #
apkurl: apk/buscoming-1.1.apk
abouttitle: 公交实时查询软件
aboutinfo: 提供南京市江宁区公交线路上公交车位置的实时定位查询。

social:
  - title: 反馈/建议留言
    url: http://javake.github.io/2015/11/06/buscoming-discuss.html
    icon: fa-commenting-o
  - title: QQ群 335195602
    url: http://shang.qq.com/wpa/qunwpa?idkey=578b7faab74c9c38842e1e868086702dce8961d2e5912c9ec944630fae085047
    icon: fa-qq
  - title: 邮件
    url: mailto:javake@outlook.com
    icon: fa-envelope-o
  - title: 作者博客
    url: http://javake.github.io
    icon: fa-list-alt
